section: screens
	TokenPC:
	Tokens-Mac-Mini:
end

section: aliases
end

section: links
	TokenPC:
		right = Tokens-Mac-Mini
	Tokens-Mac-Mini:
		left = TokenPC
end

section: options
	protocol = barrier
	relativeMouseMoves = false
	win32KeepForeground = false
	defaultLockToScreenState = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 3072
	switchCorners = none
	switchCornerSize = 0
end
