#!/usr/bin/env bash
# shell-init.sh — Single entry point for Imperium shell initialization
# TAGS: shell, init, profile, shared
#
# Source this ONE file from each machine's shell profile (.bashrc / .zshenv).
# It handles all NAS-hosted tooling setup so machine profiles stay minimal.
#
# Usage in ~/.bashrc (WSL):
#   if [[ -r /mnt/imperium/Token-OS/cli-tools/lib/shell-init.sh ]]; then
#       source /mnt/imperium/Token-OS/cli-tools/lib/shell-init.sh
#   elif [[ -f ~/.imperium-shell-cache ]]; then
#       source ~/.imperium-shell-cache
#   fi
#
# Usage in ~/.zshenv (Mac):
#   if [[ -r /Volumes/Imperium/Token-OS/cli-tools/lib/shell-init.sh ]]; then
#       source /Volumes/Imperium/Token-OS/cli-tools/lib/shell-init.sh
#   elif [[ -f ~/.imperium-shell-cache ]]; then
#       source ~/.imperium-shell-cache
#   fi

_SHELL_INIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")" && pwd)"

# ============================================================
# Non-interactive init (PATH, env vars, tmux guard)
# Inherited by scripts and subshells
# ============================================================

# 1. Machine identity + config exports (IMPERIUM, CLI_TOOLS, TOKEN_API_URL, etc.)
source "$_SHELL_INIT_DIR/nas-path.sh"

# 2. CLI tools on PATH
export PATH="$CLI_TOOLS/bin:$PATH"

# 3. tmux send-keys guard — intercepts all send-keys calls to protect user input
source "$_SHELL_INIT_DIR/tmux-guard-wrapper.sh"

# ============================================================
# Interactive init (aliases, functions, key bindings)
# Only for terminals, not scripts
# ============================================================

if [[ $- == *i* ]]; then
    # Cross-platform aliases and functions
    source "$_SHELL_INIT_DIR/shell-aliases.sh"

    # Shell-specific additions (history keys, source() override, c() hook)
    if [[ -n "${ZSH_VERSION:-}" ]]; then
        source "$_SHELL_INIT_DIR/shell-aliases-zsh.sh"
    else
        source "$_SHELL_INIT_DIR/shell-aliases-bash.sh"
    fi
fi

# ============================================================
# Offline cache — write last-known-good env vars for NAS-down fallback
# ============================================================
# The calling profile wraps `source shell-init.sh` with a file check
# and falls back to this cache if the NAS is unreachable.

cat > "$HOME/.imperium-shell-cache" 2>/dev/null << _IMPERIUM_CACHE_EOF
# Imperium shell cache — auto-generated by shell-init.sh
# Last updated: $(date -Iseconds 2>/dev/null || date)
# Provides basic env vars when NAS is offline. No functions or aliases.
export IMPERIUM_MACHINE="$IMPERIUM_MACHINE"
export IMPERIUM="$IMPERIUM"
export CIVIC="${CIVIC:-}"
export TOKEN_OS="$TOKEN_OS"
export CLI_TOOLS="$CLI_TOOLS"
export TOKEN_API_URL="$TOKEN_API_URL"
_IMPERIUM_CACHE_EOF

unset _SHELL_INIT_DIR
